### ISSUE TITLE
Копировать в буфер обмена

### ISSUE THREAD

**Issue by wokalek** [multiprogramm/RectShot#1]
Чаще всего нужно копировать именно в буфер обмена, чтобы пересылать в чаты и прочее.

`RectShot.ini`
CopyToClipboard=true

**Comment by multiprogramm** [comment]
В буфер обмена кладётся путь к файлу, который уже можно легко вставлять в любой диалог открытия файла, т.е. в том числе и для прикрепления куда-то.

**Comment by wokalek** [comment]
Это понятно, но чаще всего тебе нужен сразу файл в буфере, а не шастать по диалогам) 
По крайней мере, было бы выходом иметь переключалку этого режима в конфиге.
